mineral_catalog/mineral_catalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.conf import settings
import debug_toolbar
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^$', views.index, name='home'),
]


#
# if settings.DEBUG:
urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

mineral_catalog/minerals/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.mineral_list, name='list'),
    url(r'^(?P<pk>\d+)$', views.mineral_detail, name='detail'),
    url(r'^random$', views.random, name='random'),
    url(r'^filter/(?P<letter>[A-Z])$', views.filter_by, name='filter'),
    url(r'^search', views.search, name='search'),
    url(r'^filter_by_category/(?P<category>[ \w]+)$', views.filter_by_category,
        name='filter_by_cate'),
]

mineral_catalog/minerals/models.py
from django.db import models
from django.db.models import CharField
from django.contrib.staticfiles import finders
import json


class Mineral(models.Model):
    name = CharField('name', max_length=255, unique=True)
    image_filename = CharField('image file', max_length=255, blank=True)
    image_caption = CharField('image caption', max_length=255, blank=True)
    category = CharField('category', max_length=255, blank=True)
    formula = CharField('formula', max_length=255, blank=True)
    strunz_classification = CharField('strunz classification',
                                      max_length=255, blank=True)
    crystal_system = CharField('crystal system', max_length=255, blank=True)
    unit_cell = CharField('unit cell', max_length=255, blank=True)
    color = CharField('color', max_length=255, blank=True)
    crystal_symmetry = CharField('crystal symmetry', max_length=255,
                                 blank=True)
    cleavage = CharField('cleavage', max_length=255, blank=True)
    mohs_scale_hardness = CharField('mohs scale hardness', max_length=255,
                                    blank=True)
    luster = CharField('luster', max_length=255, blank=True)
    streak = CharField('streak', max_length=255, blank=True)
    diaphaneity = CharField('diaphaneity', max_length=255, blank=True)
    optical_properties = CharField('optical properties', max_length=255,
                                   blank=True)
    refractive_index = CharField('refractive index', max_length=255,
                                 blank=True)
    crystal_habit = CharField('crystal habit', max_length=255, blank=True)
    specific_gravity = CharField('specific gravity', max_length=255,
                                 blank=True)
    group = CharField('group', max_length=255, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


def initialize():
    with open(finders.find('minerals/data/minerals.json')) as jsonFile:
        minerals = json.load(jsonFile)
        for mineral in minerals:
            mineral = {'_'.join(key.split()): val for key, val in
                       mineral.items()}
            Mineral.objects.update_or_create(**mineral)

mineral_catalog/mineral_catalog/views.py
from django.shortcuts import redirect


def index(_):
    return redirect('minerals:list')

mineral_catalog/minerals/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Mineral


def mineral_list(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/list.html', {'minerals': minerals})


def mineral_detail(request, pk):
    mineral = get_object_or_404(Mineral, pk=pk)
    mineral.fields = mineral._meta.fields
    return render(request, 'minerals/detail.html', {'mineral': mineral})


def random(_):
    mineral = Mineral.objects.order_by('?')[0]
    return redirect('minerals:detail', pk=mineral.pk)


def filter_by(request, letter):
    minerals = Mineral.objects.filter(name__istartswith=letter)
    return render(request, 'minerals/list.html', {'minerals': minerals,
                                                  'letter': letter.upper()})


def search(request):
    minerals = Mineral.objects.filter(name__icontains=request.GET.get('q'))
    return render(request, 'minerals/list.html', {'minerals': minerals})


def filter_by_category(request, category):
    categories = [
        'Silicate',
        'Oxide',
        'Sulfate',
        'Sulfide',
        'Carbonate',
        'Halide',
        'Sulfosalt',
        'Phosphate',
        'Borate',
        'Organic',
        'Arsenate',
        'Native',
    ]
    if category == 'Other':
        minerals = Mineral.objects.exclude(category__in=categories)
    else:
        minerals = Mineral.objects.filter(category__iexact=category)
    return render(request, 'minerals/list.html', {'minerals': minerals,
                                                  'category': category})

mineral_catalog/minerals/templates/minerals/detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load mineral_field %}

{% block content %}
<div class="grid-100 mineral__container">
  <h1 class="mineral__name">{{ mineral.name|title }}</h1>
  <div class="mineral__image-bg">
    <img class="mineral__image" src="{% static 'minerals/data/images/' %}{{  mineral.name|title }}.jpg">
    <p class="mineral__caption">{{ mineral.image_caption }}</p>
  </div>
  <div class="mineral__table-container">
    <table class="mineral__table">
        {% for field in mineral.fields %}
        {% if field.name != 'image_filename' and field.name != 'image_caption' and field.name != 'id' %}
        {% render_mineral_field mineral field %}
        {% endif %}
        {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

mineral_catalog/minerals/templates/minerals/list.html
{% extends 'base.html' %}

{% block content %}
<div class="grid-100">
  <ul class="minerals__container">
    {% for mineral in minerals %}
    <li class="minerals__item">
      <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name|title }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

{% block javascript %}
<script>
    {% if letter %}
        $(".alphabet-filter-bar a:contains('A')").attr('class', '');
        const selected = $(".alphabet-filter-bar a:contains('{{ letter }}')");
        selected.attr('class', 'selected');
    {% endif %}
    {% if category %}
        const selectedCategory = document.getElementById('{{ category }}');
        selectedCategory.className = 'selected';
    {% endif %}
</script>
{% endblock %}

mineral_catalog/minerals/templates/minerals/render_field.html
{% if value != '' %}
<tr>
    <td class="mineral__category">{{ field.verbose_name|title }}</td>
    {% if field.name == 'formula' %}
    <td class="mineral__formula">{{ value|safe }}</td>
    {% else %}
    <td>{{ value }}</td>
    {% endif %}
</tr>
{% endif %}

mineral_catalog/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Macky's Minerals: A magnificant catalog of minerals{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="bounds">
    <div class="grid-100">
        <a href="{% url 'minerals:list' %}">
            <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
            </svg>
            <h1 class="logo__name text-centered">Macky's Minerals</h1>
        </a>
        <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    <div class="grid-100 alphabet-filter-bar">
        <a href="{% url 'minerals:filter' letter='A' %}">A</a>
        <a href="{% url 'minerals:filter' letter='B' %}">B</a>
        <a href="{% url 'minerals:filter' letter='C' %}">C</a>
        <a href="{% url 'minerals:filter' letter='D' %}">D</a>
        <a href="{% url 'minerals:filter' letter='E' %}">E</a>
        <a href="{% url 'minerals:filter' letter='F' %}">F</a>
        <a href="{% url 'minerals:filter' letter='G' %}">G</a>
        <a href="{% url 'minerals:filter' letter='H' %}">H</a>
        <a href="{% url 'minerals:filter' letter='I' %}">I</a>
        <a href="{% url 'minerals:filter' letter='J' %}">J</a>
        <a href="{% url 'minerals:filter' letter='K' %}">K</a>
        <a href="{% url 'minerals:filter' letter='L' %}">L</a>
        <a href="{% url 'minerals:filter' letter='M' %}">M</a>
        <a href="{% url 'minerals:filter' letter='N' %}">N</a>
        <a href="{% url 'minerals:filter' letter='O' %}">O</a>
        <a href="{% url 'minerals:filter' letter='P' %}">P</a>
        <a href="{% url 'minerals:filter' letter='Q' %}">Q</a>
        <a href="{% url 'minerals:filter' letter='R' %}">R</a>
        <a href="{% url 'minerals:filter' letter='S' %}">S</a>
        <a href="{% url 'minerals:filter' letter='T' %}">T</a>
        <a href="{% url 'minerals:filter' letter='U' %}">U</a>
        <a href="{% url 'minerals:filter' letter='V' %}">V</a>
        <a href="{% url 'minerals:filter' letter='W' %}">W</a>
        <a href="{% url 'minerals:filter' letter='X' %}">X</a>
        <a href="{% url 'minerals:filter' letter='Y' %}">Y</a>
        <a href="{% url 'minerals:filter' letter='Z' %}">Z</a>
    </div>
    <main class="grid-100">
        <div class="main-nav">
            <form action="{% url 'minerals:search' %}" method="GET" class="search-form">
                <input type="search" name="q" class="search-box">
                <input type="submit" value="Search" class="search-button">
            </form>
            <h2 class="category-heading">Category</h2>
            <ul class="category-ul">
                <li><a id="Silicate" href="{% url 'minerals:filter_by_cate' category='Silicate' %}">Silicates</a></li>
                <li><a id="Oxide" href="{% url 'minerals:filter_by_cate' category='Oxide' %}">Oxides</a></li>
                <li><a id="Sulfate" href="{% url 'minerals:filter_by_cate' category='Sulfate' %}">Sulfates</a></li>
                <li><a id="Sulfide" href="{% url 'minerals:filter_by_cate' category='Sulfide' %}">Sulfides</a></li>
                <li><a id="Carbonate" href="{% url 'minerals:filter_by_cate' category='Carbonate' %}">Carbonates</a></li>
                <li><a id="Halide" href="{% url 'minerals:filter_by_cate' category='Halide' %}">Halides</a></li>
                <li><a id="Sulfosalt" href="{% url 'minerals:filter_by_cate' category='Sulfosalt' %}">Sulfosalts</a></li>
                <li><a id="Phosphate" href="{% url 'minerals:filter_by_cate' category='Phosphate' %}">Phosphates</a></li>
                <li><a id="Borate" href="{% url 'minerals:filter_by_cate' category='Borate' %}">Borates</a></li>
                <li><a id="Organic" href="{% url 'minerals:filter_by_cate' category='Organic' %}">Organic Minerals</a></li>
                <li><a id="Arsenate" href="{% url 'minerals:filter_by_cate' category='Arsenate' %}">Arsenates</a></li>
                <li><a id="Native" href="{% url 'minerals:filter_by_cate' category='Native' %}">Native Elements</a></li>
                <li><a id="Other" href="{% url 'minerals:filter_by_cate' category='Other' %}">Other</a></li>
            </ul>
        </div>
        {% block content %}{% endblock %}
    </main>
</div>
  <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:random' %}">Show random mineral</a>
  </div>
    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous">
    </script>
    {% block javascript %}{% endblock %}
</body>
</html>